### PR TITLE
0.2.0 release

### PR DESCRIPTION
**Pull request by sneal**
@mwrock Release for #3 with small refactoring to pass Rubocop. Still need to redesign the runner to take a command_executor.

### CODE REVIEW

**Comment by mwrock** [comment]
:+1:

**Comment by jerryk55** [comment]
@sneal @mwrock Thanks so much for merging these last two PRs.  What's your normal timeframe for pushing versions out to RubyGems?   Inquiring minds and all that.... :-)

**Comment by mwrock** [comment]
I just released now. My apologies. I should have done this yesterday after merging @sneal's version bump.

**Comment by jerryk55** [comment]
Yay!!!  Thanks much.

**Pull request merged**
